'use client'

import { useState, useEffect } from 'react'
import {
  Plus,
  RefreshCw,
  HelpCircle,
  Check,
  Sparkles,
  MessageSquare,
  ExternalLink,
  Trash2,
  ChevronRight,
} from 'lucide-react'
import { B2C_CONTEXTS, B2B_CONTEXTS } from './configs/niche-finder.config'

// Types
interface KeywordItem {
  id: string
  label: string
  selected: boolean
  category?: string
}

interface SourcesConfig {
  reddit_general: {
    enabled: boolean
  }
  reddit: {
    enabled: boolean
    subreddits: string[]
  }
  thematic_forums: {
    enabled: boolean
    forums: string[]
  }
  general_forums: {
    enabled: boolean
    forums: string[]
  }
}

interface KeywordConfigPanelProps {
  contextType: 'personal' | 'business' | 'both'
  product?: string
  target?: string
  lifeContexts: KeywordItem[]
  needWords: KeywordItem[]
  indicators: KeywordItem[]
  sources: SourcesConfig
  onLifeContextsChange: (items: KeywordItem[]) => void
  onNeedWordsChange: (items: KeywordItem[]) => void
  onIndicatorsChange: (items: KeywordItem[]) => void
  onSourcesChange: (sources: SourcesConfig) => void
  onGenerateNeedWords: () => Promise<void>
  onGenerateSubreddits: () => Promise<void>
  onGenerateForums: () => Promise<void>
  onContinue: () => void
  isGeneratingNeedWords?: boolean
  isGeneratingSubreddits?: boolean
  isGeneratingForums?: boolean
}

// Tooltip component
function Tooltip({ children, content }: { children: React.ReactNode; content: string }) {
  const [show, setShow] = useState(false)

  return (
    <div className="relative inline-block">
      <div
        onMouseEnter={() => setShow(true)}
        onMouseLeave={() => setShow(false)}
      >
        {children}
      </div>
      {show && (
        <div className="absolute z-50 bottom-full left-1/2 -translate-x-1/2 mb-2 px-3 py-2 bg-gray-900 text-white text-xs rounded-lg shadow-lg max-w-xs whitespace-normal">
          {content}
          <div className="absolute top-full left-1/2 -translate-x-1/2 -mt-1 border-4 border-transparent border-t-gray-900" />
        </div>
      )}
    </div>
  )
}

// Main component
export default function KeywordConfigPanel({
  contextType,
  product,
  target,
  lifeContexts,
  needWords,
  indicators,
  sources,
  onLifeContextsChange,
  onNeedWordsChange,
  onIndicatorsChange,
  onSourcesChange,
  onGenerateNeedWords,
  onGenerateSubreddits,
  onGenerateForums,
  onContinue,
  isGeneratingNeedWords,
  isGeneratingSubreddits,
  isGeneratingForums,
}: KeywordConfigPanelProps) {
  const [newContextItem, setNewContextItem] = useState('')
  const [newNeedWord, setNewNeedWord] = useState('')
  const [newIndicator, setNewIndicator] = useState('')
  const [newSubreddit, setNewSubreddit] = useState('')
  const [newForum, setNewForum] = useState('')
  const [hasAutoGenerated, setHasAutoGenerated] = useState(false)

  // Initialize life contexts if empty
  useEffect(() => {
    if (lifeContexts.length === 0) {
      let contexts: Array<{ id: string; label: string; category: string; contextType: string }> = []
      if (contextType === 'personal' || contextType === 'both') {
        contexts = [...contexts, ...B2C_CONTEXTS]
      }
      if (contextType === 'business' || contextType === 'both') {
        contexts = [...contexts, ...B2B_CONTEXTS]
      }
      onLifeContextsChange(contexts.map(c => ({
        id: c.id,
        label: c.label,
        category: c.category,
        selected: false,
      })))
    }
  }, [contextType, lifeContexts.length, onLifeContextsChange])

  // Initialize sources if empty
  useEffect(() => {
    if (!sources.reddit && !sources.thematic_forums) {
      onSourcesChange({
        reddit_general: { enabled: false },
        reddit: { enabled: true, subreddits: [] },
        thematic_forums: { enabled: true, forums: [] },
        general_forums: { enabled: false, forums: [] },
      })
    }
  }, [sources, onSourcesChange])

  // Auto-generate need words on mount if empty, or provide defaults
  useEffect(() => {
    console.log('[KeywordConfigPanel] needWords effect:', {
      needWordsLength: needWords.length,
      isGeneratingNeedWords,
      hasAutoGenerated,
      product,
    })
    if (needWords.length === 0 && !isGeneratingNeedWords && !hasAutoGenerated) {
      if (product) {
        // If product is defined, generate via LLM
        console.log('[KeywordConfigPanel] Generating need words via LLM for product:', product)
        setHasAutoGenerated(true)
        onGenerateNeedWords()
      } else {
        // Otherwise, provide generic default need words
        console.log('[KeywordConfigPanel] No product, using default need words')
        setHasAutoGenerated(true)
        const defaultNeedWords = [
          { id: 'problema', label: 'problema', selected: false },
          { id: 'solucion', label: 'solución', selected: false },
          { id: 'ayuda', label: 'ayuda', selected: false },
          { id: 'recomendacion', label: 'recomendación', selected: false },
          { id: 'opinion', label: 'opinión', selected: false },
          { id: 'consejo', label: 'consejo', selected: false },
          { id: 'experiencia', label: 'experiencia', selected: false },
          { id: 'alternativa', label: 'alternativa', selected: false },
          { id: 'comparacion', label: 'comparación', selected: false },
          { id: 'precio', label: 'precio', selected: false },
          { id: 'calidad', label: 'calidad', selected: false },
          { id: 'servicio', label: 'servicio', selected: false },
        ]
        onNeedWordsChange(defaultNeedWords)
      }
    }
  }, [needWords.length, isGeneratingNeedWords, hasAutoGenerated, product, onGenerateNeedWords, onNeedWordsChange])

  // Initialize indicators with defaults if empty
  useEffect(() => {
    if (indicators.length === 0) {
      const defaultIndicators = [
        { id: 'harto', label: 'estoy harto de', selected: false },
        { id: 'no_aguanto', label: 'no aguanto más', selected: false },
        { id: 'frustrante', label: 'es frustrante', selected: false },
        { id: 'ayuda_urgente', label: 'necesito ayuda urgente', selected: false },
        { id: 'no_funciona', label: 'no funciona', selected: false },
        { id: 'imposible', label: 'es imposible', selected: false },
        { id: 'desesperado', label: 'estoy desesperado', selected: false },
        { id: 'cansado', label: 'cansado de', selected: false },
        { id: 'no_se_que_hacer', label: 'no sé qué hacer', selected: false },
        { id: 'problema_grave', label: 'problema grave', selected: false },
        { id: 'odio', label: 'odio cuando', selected: false },
        { id: 'molesta', label: 'me molesta', selected: false },
      ]
      onIndicatorsChange(defaultIndicators)
    }
  }, [indicators.length, onIndicatorsChange])

  // Group contexts by category
  const groupedContexts = lifeContexts.reduce((acc, item) => {
    const cat = item.category || 'Otros'
    if (!acc[cat]) acc[cat] = []
    acc[cat].push(item)
    return acc
  }, {} as Record<string, KeywordItem[]>)

  // Handlers
  const toggleContext = (id: string) => {
    onLifeContextsChange(lifeContexts.map(c =>
      c.id === id ? { ...c, selected: !c.selected } : c
    ))
  }

  const toggleNeedWord = (id: string) => {
    onNeedWordsChange(needWords.map(w =>
      w.id === id ? { ...w, selected: !w.selected } : w
    ))
  }

  const toggleIndicator = (id: string) => {
    onIndicatorsChange(indicators.map(i =>
      i.id === id ? { ...i, selected: !i.selected } : i
    ))
  }

  const addCustomContext = () => {
    if (!newContextItem.trim()) return
    onLifeContextsChange([...lifeContexts, {
      id: `custom_${Date.now()}`,
      label: newContextItem.trim(),
      selected: true,
    }])
    setNewContextItem('')
  }

  const addCustomNeedWord = () => {
    if (!newNeedWord.trim()) return
    onNeedWordsChange([...needWords, {
      id: `custom_${Date.now()}`,
      label: newNeedWord.trim(),
      selected: true,
    }])
    setNewNeedWord('')
  }

  const addCustomIndicator = () => {
    if (!newIndicator.trim()) return
    onIndicatorsChange([...indicators, {
      id: `custom_${Date.now()}`,
      label: newIndicator.trim(),
      selected: true,
    }])
    setNewIndicator('')
  }

  const addSubreddit = () => {
    if (!newSubreddit.trim()) return
    const sub = newSubreddit.trim().replace(/^r\//, '')
    if (!sources.reddit.subreddits.includes(sub)) {
      onSourcesChange({
        ...sources,
        reddit: {
          ...sources.reddit,
          subreddits: [...sources.reddit.subreddits, sub],
        },
      })
    }
    setNewSubreddit('')
  }

  const removeSubreddit = (sub: string) => {
    onSourcesChange({
      ...sources,
      reddit: {
        ...sources.reddit,
        subreddits: sources.reddit.subreddits.filter(s => s !== sub),
      },
    })
  }

  const addForum = () => {
    if (!newForum.trim()) return
    let url = newForum.trim()
    if (!url.startsWith('http')) url = 'https://' + url
    if (!sources.thematic_forums.forums.includes(url)) {
      onSourcesChange({
        ...sources,
        thematic_forums: {
          ...sources.thematic_forums,
          forums: [...sources.thematic_forums.forums, url],
        },
      })
    }
    setNewForum('')
  }

  const removeForum = (url: string) => {
    onSourcesChange({
      ...sources,
      thematic_forums: {
        ...sources.thematic_forums,
        forums: sources.thematic_forums.forums.filter(f => f !== url),
      },
    })
  }

  // Calculations
  const selectedContexts = lifeContexts.filter(c => c.selected)
  const selectedNeeds = needWords.filter(w => w.selected)
  const selectedIndicators = indicators.filter(i => i.selected)
  const redditGeneralCount = sources.reddit_general?.enabled ? 1 : 0
  const subredditsCount = sources.reddit?.subreddits?.length || 0
  const forumsCount = sources.thematic_forums?.forums?.length || 0
  const totalSources = redditGeneralCount + subredditsCount + forumsCount

  const canContinue = selectedContexts.length > 0 && selectedNeeds.length > 0 && totalSources > 0

  return (
    <div className="space-y-8">
      {/* SECTION 1: Situaciones / Condiciones */}
      <section>
        <div className="flex items-center gap-2 mb-3">
          <h2 className="text-lg font-semibold text-gray-900">
            {contextType === 'business' ? '🏢 Condiciones del Negocio' :
             contextType === 'personal' ? '👤 Situaciones de Vida' :
             '👤 Situaciones y Condiciones'}
          </h2>
          <Tooltip content={
            contextType === 'business'
              ? 'Tipo de empresa o etapa en la que se encuentra: startup, PYME, en expansión, etc.'
              : 'Contexto de vida de tu cliente: padre, estudiante, emprendedor, etc.'
          }>
            <HelpCircle size={16} className="text-gray-400 cursor-help" />
          </Tooltip>
          <span className="ml-auto text-sm text-gray-500">
            {selectedContexts.length} seleccionadas
          </span>
        </div>

        <div className="space-y-4">
          {Object.entries(groupedContexts).map(([category, items]) => (
            <div key={category}>
              <h4 className="text-xs font-medium text-gray-500 uppercase tracking-wide mb-2">{category}</h4>
              <div className="flex flex-wrap gap-2">
                {items.map(item => (
                  <button
                    key={item.id}
                    onClick={() => toggleContext(item.id)}
                    className={`px-3 py-1.5 rounded-full text-sm transition-all ${
                      item.selected
                        ? 'bg-blue-600 text-white'
                        : 'bg-gray-100 text-gray-700 hover:bg-gray-200'
                    }`}
                  >
                    {item.label}
                    {item.selected && <Check size={14} className="inline ml-1" />}
                  </button>
                ))}
              </div>
            </div>
          ))}

          {/* Add custom */}
          <div className="flex gap-2">
            <input
              type="text"
              value={newContextItem}
              onChange={(e) => setNewContextItem(e.target.value)}
              onKeyDown={(e) => e.key === 'Enter' && addCustomContext()}
              placeholder="Agregar otra..."
              className="flex-1 px-3 py-1.5 text-sm border border-gray-200 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-200"
            />
            <button
              onClick={addCustomContext}
              disabled={!newContextItem.trim()}
              className="px-3 py-1.5 bg-gray-100 text-gray-600 rounded-lg hover:bg-gray-200 disabled:opacity-50"
            >
              <Plus size={16} />
            </button>
          </div>
        </div>
      </section>

      {/* SECTION 2: Palabras de Necesidad */}
      <section>
        <div className="flex items-center gap-2 mb-3">
          <h2 className="text-lg font-semibold text-gray-900">🔍 Palabras de Necesidad</h2>
          <Tooltip content='Palabras que la gente usa cuando busca ayuda: "problemas con", "cómo hacer", "necesito", etc.'>
            <HelpCircle size={16} className="text-gray-400 cursor-help" />
          </Tooltip>
          <span className="ml-auto text-sm text-gray-500">
            {selectedNeeds.length} seleccionadas
          </span>
        </div>

        {/* Seleccionadas - persisten al regenerar */}
        {selectedNeeds.length > 0 && (
          <div className="mb-4 p-3 bg-green-50 rounded-lg border border-green-200">
            <div className="flex items-center gap-2 mb-2">
              <Check size={14} className="text-green-600" />
              <span className="text-xs font-medium text-green-700 uppercase tracking-wide">Seleccionadas</span>
            </div>
            <div className="flex flex-wrap gap-2">
              {selectedNeeds.map(word => (
                <button
                  key={word.id}
                  onClick={() => toggleNeedWord(word.id)}
                  className="px-3 py-1.5 rounded-full text-sm bg-green-600 text-white hover:bg-green-700 transition-all"
                >
                  {word.label}
                  <Check size={14} className="inline ml-1" />
                </button>
              ))}
            </div>
          </div>
        )}

        {/* Sugerencias - se reemplazan al regenerar */}
        {isGeneratingNeedWords ? (
          <div className="flex items-center gap-2 py-4 text-gray-500">
            <RefreshCw size={16} className="animate-spin" />
            <span>Generando sugerencias con IA...</span>
          </div>
        ) : (
          <>
            {needWords.filter(w => !w.selected).length > 0 && (
              <div className="mb-3">
                <div className="flex items-center gap-2 mb-2">
                  <Sparkles size={14} className="text-gray-400" />
                  <span className="text-xs font-medium text-gray-500 uppercase tracking-wide">Sugerencias</span>
                </div>
                <div className="flex flex-wrap gap-2">
                  {needWords.filter(w => !w.selected).map(word => (
                    <button
                      key={word.id}
                      onClick={() => toggleNeedWord(word.id)}
                      className="px-3 py-1.5 rounded-full text-sm bg-gray-100 text-gray-700 hover:bg-green-100 hover:text-green-700 transition-all"
                    >
                      {word.label}
                    </button>
                  ))}
                </div>
              </div>
            )}

            {/* Regenerar + Agregar custom */}
            <div className="flex gap-2">
              <button
                onClick={onGenerateNeedWords}
                disabled={isGeneratingNeedWords}
                className="flex items-center gap-1.5 px-3 py-1.5 text-sm text-blue-600 hover:bg-blue-50 rounded-lg transition-colors"
              >
                <Sparkles size={14} />
                {needWords.filter(w => !w.selected).length > 0 ? 'Regenerar sugerencias' : 'Generar sugerencias'}
              </button>
              <input
                type="text"
                value={newNeedWord}
                onChange={(e) => setNewNeedWord(e.target.value)}
                onKeyDown={(e) => e.key === 'Enter' && addCustomNeedWord()}
                placeholder="Agregar palabra..."
                className="flex-1 px-3 py-1.5 text-sm border border-gray-200 rounded-lg focus:outline-none focus:ring-2 focus:ring-green-200"
              />
              <button
                onClick={addCustomNeedWord}
                disabled={!newNeedWord.trim()}
                className="px-3 py-1.5 bg-gray-100 text-gray-600 rounded-lg hover:bg-gray-200 disabled:opacity-50"
              >
                <Plus size={16} />
              </button>
            </div>
          </>
        )}
      </section>

      {/* SECTION 3: Señales de Frustración (Opcional) */}
      <section>
        <div className="flex items-center gap-2 mb-3">
          <h2 className="text-lg font-semibold text-gray-900">😤 Señales de Frustración</h2>
          <span className="text-xs text-gray-400 bg-gray-100 px-2 py-0.5 rounded">Opcional</span>
          <Tooltip content='Palabras que indican urgencia: "estoy harto", "no aguanto", "ayuda urgente". Ayudan a filtrar los casos más urgentes.'>
            <HelpCircle size={16} className="text-gray-400 cursor-help" />
          </Tooltip>
          <span className="ml-auto text-sm text-gray-500">
            {selectedIndicators.length} seleccionadas
          </span>
        </div>

        {indicators.length > 0 && (
          <div className="flex flex-wrap gap-2 mb-3">
            {indicators.map(ind => (
              <button
                key={ind.id}
                onClick={() => toggleIndicator(ind.id)}
                className={`px-3 py-1.5 rounded-full text-sm transition-all ${
                  ind.selected
                    ? 'bg-amber-500 text-white'
                    : 'bg-gray-100 text-gray-700 hover:bg-gray-200'
                }`}
              >
                {ind.label}
                {ind.selected && <Check size={14} className="inline ml-1" />}
              </button>
            ))}
          </div>
        )}

        <div className="flex gap-2">
          <input
            type="text"
            value={newIndicator}
            onChange={(e) => setNewIndicator(e.target.value)}
            onKeyDown={(e) => e.key === 'Enter' && addCustomIndicator()}
            placeholder='Agregar señal (ej: "estoy harto de")'
            className="flex-1 px-3 py-1.5 text-sm border border-gray-200 rounded-lg focus:outline-none focus:ring-2 focus:ring-amber-200"
          />
          <button
            onClick={addCustomIndicator}
            disabled={!newIndicator.trim()}
            className="px-3 py-1.5 bg-gray-100 text-gray-600 rounded-lg hover:bg-gray-200 disabled:opacity-50"
          >
            <Plus size={16} />
          </button>
        </div>
      </section>

      {/* SECTION 4: Dónde Buscar */}
      <section>
        <div className="flex items-center gap-2 mb-4">
          <h2 className="text-lg font-semibold text-gray-900">🌐 Dónde Buscar</h2>
          <Tooltip content="Fuentes donde buscar conversaciones: Reddit, foros especializados de tu industria.">
            <HelpCircle size={16} className="text-gray-400 cursor-help" />
          </Tooltip>
          <span className="ml-auto text-sm text-gray-500">
            {totalSources} fuentes
          </span>
        </div>

        {/* Reddit General Toggle */}
        <div className="mb-4 p-3 bg-gray-50 rounded-lg border border-gray-200">
          <label className="flex items-center gap-3 cursor-pointer">
            <input
              type="checkbox"
              checked={sources.reddit_general?.enabled || false}
              onChange={(e) => onSourcesChange({
                ...sources,
                reddit_general: { enabled: e.target.checked },
              })}
              className="w-5 h-5 rounded border-gray-300 text-orange-600 focus:ring-orange-500"
            />
            <span className="text-2xl">🔶</span>
            <div className="flex-1">
              <span className="font-medium text-gray-900">Reddit General</span>
              <p className="text-xs text-gray-500">Buscar en todo Reddit (sin filtrar por subreddit)</p>
            </div>
          </label>
        </div>

        <div className="grid md:grid-cols-2 gap-6">
          {/* Subreddits específicos */}
          <div className="p-4 bg-orange-50 rounded-xl border border-orange-100">
            <div className="flex items-center gap-2 mb-3">
              <span className="text-xl">📍</span>
              <h3 className="font-medium text-gray-900">Subreddits Específicos</h3>
              <span className="text-xs text-gray-500 ml-auto">
                {subredditsCount} subreddits
              </span>
            </div>

            {subredditsCount > 0 && (
              <div className="flex flex-wrap gap-2 mb-3">
                {sources.reddit.subreddits.map(sub => (
                  <span
                    key={sub}
                    className="inline-flex items-center gap-1 px-2.5 py-1 bg-white border border-orange-200 rounded-full text-sm text-orange-700"
                  >
                    r/{sub}
                    <button onClick={() => removeSubreddit(sub)} className="hover:text-orange-900">
                      <Trash2 size={12} />
                    </button>
                  </span>
                ))}
              </div>
            )}

            <div className="flex gap-2 mb-2">
              <input
                type="text"
                value={newSubreddit}
                onChange={(e) => setNewSubreddit(e.target.value)}
                onKeyDown={(e) => e.key === 'Enter' && addSubreddit()}
                placeholder="Agregar subreddit..."
                className="flex-1 px-3 py-1.5 text-sm text-gray-900 placeholder-gray-400 bg-white border border-orange-200 rounded-lg focus:outline-none focus:ring-2 focus:ring-orange-200"
              />
              <button
                onClick={addSubreddit}
                disabled={!newSubreddit.trim()}
                className="px-3 py-1.5 bg-orange-100 text-orange-700 rounded-lg hover:bg-orange-200 disabled:opacity-50"
              >
                <Plus size={16} />
              </button>
            </div>

            <button
              onClick={onGenerateSubreddits}
              disabled={isGeneratingSubreddits}
              className="w-full flex items-center justify-center gap-1.5 px-3 py-1.5 text-sm text-orange-600 hover:bg-orange-100 rounded-lg transition-colors"
            >
              {isGeneratingSubreddits ? (
                <>
                  <RefreshCw size={14} className="animate-spin" />
                  Buscando...
                </>
              ) : (
                <>
                  <Sparkles size={14} />
                  Sugerir subreddits con IA
                </>
              )}
            </button>
          </div>

          {/* Foros */}
          <div className="p-4 bg-purple-50 rounded-xl border border-purple-100">
            <div className="flex items-center gap-2 mb-3">
              <MessageSquare size={20} className="text-purple-500" />
              <h3 className="font-medium text-gray-900">Foros Temáticos</h3>
              <span className="text-xs text-gray-500 ml-auto">
                {forumsCount} foros
              </span>
            </div>

            {forumsCount > 0 && (
              <div className="space-y-1.5 mb-3">
                {sources.thematic_forums.forums.map(url => (
                  <div
                    key={url}
                    className="flex items-center gap-2 px-2.5 py-1.5 bg-white border border-purple-200 rounded-lg text-sm"
                  >
                    <ExternalLink size={12} className="text-purple-400" />
                    <span className="flex-1 text-purple-700 truncate">
                      {url.replace(/^https?:\/\/(www\.)?/, '').replace(/\/$/, '')}
                    </span>
                    <button onClick={() => removeForum(url)} className="text-purple-400 hover:text-purple-700">
                      <Trash2 size={12} />
                    </button>
                  </div>
                ))}
              </div>
            )}

            <div className="flex gap-2 mb-2">
              <input
                type="text"
                value={newForum}
                onChange={(e) => setNewForum(e.target.value)}
                onKeyDown={(e) => e.key === 'Enter' && addForum()}
                placeholder="URL del foro..."
                className="flex-1 px-3 py-1.5 text-sm text-gray-900 placeholder-gray-400 bg-white border border-purple-200 rounded-lg focus:outline-none focus:ring-2 focus:ring-purple-200"
              />
              <button
                onClick={addForum}
                disabled={!newForum.trim()}
                className="px-3 py-1.5 bg-purple-100 text-purple-700 rounded-lg hover:bg-purple-200 disabled:opacity-50"
              >
                <Plus size={16} />
              </button>
            </div>

            <button
              onClick={onGenerateForums}
              disabled={isGeneratingForums}
              className="w-full flex items-center justify-center gap-1.5 px-3 py-1.5 text-sm text-purple-600 hover:bg-purple-100 rounded-lg transition-colors"
            >
              {isGeneratingForums ? (
                <>
                  <RefreshCw size={14} className="animate-spin" />
                  Buscando...
                </>
              ) : (
                <>
                  <Sparkles size={14} />
                  Sugerir foros con IA
                </>
              )}
            </button>
          </div>
        </div>
      </section>

      {/* Summary & Continue */}
      <div className="border-t pt-6">
        {canContinue && (
          <div className="bg-blue-50 border border-blue-100 rounded-lg p-4 mb-4">
            <div className="flex flex-col gap-1 text-sm">
              <div className="flex items-center justify-between">
                <span className="text-blue-700">
                  <strong>{selectedContexts.length}</strong> situaciones × <strong>{selectedNeeds.length}</strong> necesidades × <strong>{totalSources}</strong> fuentes
                  {selectedIndicators.length > 0 && (
                    <span className="text-blue-500"> × <strong>{selectedIndicators.length + 1}</strong> variantes</span>
                  )}
                </span>
                <span className="text-blue-600 font-semibold">
                  = <strong>{selectedContexts.length * selectedNeeds.length * totalSources * (selectedIndicators.length > 0 ? (selectedIndicators.length + 1) : 1)}</strong> búsquedas
                </span>
              </div>
              {selectedIndicators.length > 0 && (
                <p className="text-xs text-blue-500">
                  {selectedIndicators.length + 1} variantes = sin señal + {selectedIndicators.length} señales seleccionadas
                </p>
              )}
            </div>
          </div>
        )}

        <button
          onClick={onContinue}
          disabled={!canContinue}
          className="w-full py-3 bg-blue-600 text-white rounded-xl font-medium hover:bg-blue-700 disabled:bg-gray-300 disabled:cursor-not-allowed transition-colors flex items-center justify-center gap-2"
        >
          {!canContinue ? (
            <>
              {selectedContexts.length === 0 && 'Selecciona situaciones'}
              {selectedContexts.length > 0 && selectedNeeds.length === 0 && 'Selecciona palabras de necesidad'}
              {selectedContexts.length > 0 && selectedNeeds.length > 0 && totalSources === 0 && 'Agrega al menos una fuente'}
            </>
          ) : (
            <>
              Buscar Conversaciones
              <ChevronRight size={18} />
            </>
          )}
        </button>
      </div>
    </div>
  )
}
