-- Emergency migration to disable RLS on all tables for development
-- This bypasses all RLS issues

-- Disable RLS on all v2 tables
ALTER TABLE IF EXISTS document_assignments DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS synthesis_jobs DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS completeness_scores DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS foundational_schemas DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS foundational_transformers DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS client_credentials DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS api_call_logs DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS user_openrouter_tokens DISABLE ROW LEVEL SECURITY;

-- Also ensure base tables have RLS disabled
ALTER TABLE IF EXISTS agencies DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS clients DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS documents DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS playbooks DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS playbook_executions DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS projects DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS agency_members DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS notifications DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS project_invitations DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS project_members DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS project_share_links DISABLE ROW LEVEL SECURITY;

-- Verify changes
SELECT 
  schemaname, 
  tablename, 
  rowsecurity 
FROM pg_tables 
WHERE schemaname = 'public' 
ORDER BY tablename;
