-- Playbook Step Outputs
-- Stores the output of each playbook step for persistence and flow continuity

CREATE TABLE IF NOT EXISTS playbook_step_outputs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  project_id UUID NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  playbook_type TEXT NOT NULL, -- 'signal_based_outreach', etc.
  step_id TEXT NOT NULL, -- 'map_topics', 'find_creators', etc.

  -- LLM output
  output_content TEXT, -- Markdown output from LLM

  -- Imported data (for scraping steps)
  imported_data JSONB, -- Parsed CSV/JSON data from external scrapers

  -- Execution context
  variables_used JSONB, -- Variables used in this execution

  -- Status tracking
  status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'running', 'completed', 'error')),
  error_message TEXT,

  -- Timestamps
  executed_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),

  -- Each project can only have one output per step per playbook type
  UNIQUE(project_id, playbook_type, step_id)
);

-- Index for fast lookups
CREATE INDEX IF NOT EXISTS idx_playbook_step_outputs_project
  ON playbook_step_outputs(project_id, playbook_type);

-- Trigger to update updated_at
CREATE OR REPLACE FUNCTION update_playbook_step_outputs_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trigger_playbook_step_outputs_updated_at ON playbook_step_outputs;
CREATE TRIGGER trigger_playbook_step_outputs_updated_at
  BEFORE UPDATE ON playbook_step_outputs
  FOR EACH ROW
  EXECUTE FUNCTION update_playbook_step_outputs_updated_at();

-- RLS disabled (same as other tables in this project)
ALTER TABLE playbook_step_outputs DISABLE ROW LEVEL SECURITY;

COMMENT ON TABLE playbook_step_outputs IS 'Stores outputs of each playbook step for persistence between sessions';
COMMENT ON COLUMN playbook_step_outputs.output_content IS 'Markdown output generated by LLM';
COMMENT ON COLUMN playbook_step_outputs.imported_data IS 'JSON data imported from external scrapers (Phantombuster, Apify CSV exports)';
COMMENT ON COLUMN playbook_step_outputs.variables_used IS 'Snapshot of variables used when executing this step';
